### ISSUE TITLE
Small things

### ISSUE THREAD

**Issue by davelab6** [appajid/Ambarisha#1]
- [x] At https://github.com/appajid/Kelvin-Kannada/settings rename the repo to `ambarisha`
- [x] At https://github.com/appajid/Kelvin-Kannada/settings add me and kelvin as collaborators with admin level access (@davelab6 and @kelvin13 are our github usernames)

**Comment by appajid** [comment]
Done

**Comment by davelab6** [comment]
Thanks! @kelvin13 please do make changes as pull requests
