### ISSUE TITLE
Lost anchor points (and kerning etc)

### ISSUE THREAD

**Issue by tayloraswift** [appajid/Ambarisha#10]
The more I look through the “release” file of Ambarisha, the more things I find have vanished…

The original Latin font contained kerning pairs and anchor points—all of these have disappeared in the release file! All the latin ligatures are gone too! And the capital accents, and a couple glyphs even :(

**Comment by tayloraswift** [comment]
I recommend we start over from [latin-Ambarisha](https://github.com/kelvin13/a-font-named-font) and merge the fonts properly instead of copy and pasting outlines as it looks like is what happened.

**Comment by davelab6** [comment]
Ambarisha Sir, I would like to suggest working with Kelvin to re-engineer
the font for high quality :)

**Comment by tayloraswift** [comment]
@appajid since the kannada font only contains ligatures, is it possible to copy the outlines into latin-Ambarisha and copy over the kannada ligature tables?

**Comment by tayloraswift** [comment]
dave the ligature tables can coexist safely right?

**Comment by davelab6** [comment]
Yes I think you can splice the GSUB and GPOS, as long as the Glyph Order is
the same.

**Comment by tayloraswift** [comment]
I tried and fontforge just gave this error
`Bad reverse encoding`
about 2138940032 times

**Comment by davelab6** [comment]
I would do it with TTX. FontForge is way too buggy, I would use it only for
drawing UFOs.

**Comment by appajid** [comment]
I just updated Kerning tables from Kelvin's font to Ambarisha. Please check it and let me know.

**Comment by tayloraswift** [comment]
The kerning tables look good, but two-thirds of the ligatures are still missing. And the Amacron character, which i would fix myself but all the capital accents and references seem to be missing from the font.

**Comment by tayloraswift** [comment]
also why may I ask is the source in this repository on a different glyph naming system than the original. That’s really screwing with the merger

for example, `acutecomb` at `U+0301` became `acutecmb` at `U+????`

**Comment by appajid** [comment]
"but two-thirds of the ligatures are still missing. And the Amacron character, which i would fix myself but all the capital accents and references seem to be missing from the font."
- I didn't understand this.. Can you post a screenshot if possible?

**Comment by tayloraswift** [comment]
the original contained capitalized versions of the accent glyphs 
![selection_015](https://cloud.githubusercontent.com/assets/2556986/14212898/af1f09a8-f7fa-11e5-81bf-1eb07262d967.png)

**Comment by tayloraswift** [comment]
but either way the naming system is completely changed in your version

**Comment by appajid** [comment]
Can you mail me latest version of your font

**Comment by tayloraswift** [comment]
it lives at [a-font-named-font](https://github.com/kelvin13/a-font-named-font)

**Comment by tayloraswift** [comment]
@appajid any progress on this?

**Comment by tayloraswift** [comment]
I think it is best if you give me simply an isolated Kannada font (no latin chars or accents, but with kannada ligatures and kerning) so that I can merge without harming or overwriting the latin chars
