### ISSUE TITLE
improve font quality

### ISSUE THREAD

**Issue by tayloraswift** [appajid/Ambarisha#11]
I merged the two fonts, at `union.sfd`, but path quality i noticed in the generated kannada ligatures is extremely poor. Excessive points, points too close together, etc. 
![selection_009](https://cloud.githubusercontent.com/assets/2556986/14372450/c37f994e-fd0e-11e5-9fb4-a320ac84ddad.png)
I also noticed the kannada alphabet is not outlined as well as it should be either. Curve points that should be HV, points that might as well be extrema points, unnecessary tangent points, non integer coordinates, inappropriate curve/corner point choices, poor overlap assembly, etc.
![selection_008](https://cloud.githubusercontent.com/assets/2556986/14372411/52eb551a-fd0e-11e5-8182-e0a62655db37.png)
Just because the typeface is a loose design doesn’t mean we can get sloppy with our outlining.

Rupee symbol is also of questionable design—it should be narrower, and really needs an optical correction with the join between top bar and the ‘R’ bowl. I can fix that one for you if you are okay with that.
![selection_010](https://cloud.githubusercontent.com/assets/2556986/14372495/1d7067f8-fd0f-11e5-8c14-16737c4cb7fe.png)
Not trying to be a pain in the butt, I just think these are minor things that really need to be ironed out before release

**Comment by davelab6** [comment]
>  Excessive points, points too close together, etc. 

@kelvin13 the oulines with so many points look like a PS -> TT -> PS conversion to me. Or use of spiros.

@appajid please can you confirm the location of your drawing file? Did you use Spiro at all?

> Not trying to be a pain in the butt, I just think these are minor things that really need to be ironed out before release

I agree. @appajid will you be able to improve this? :)

**Comment by tayloraswift** [comment]
@appajid pinggg

**Comment by appajid** [comment]
Hi,
1. I don't use Spiro.  May be it's a problem while taking glyphs from Fontographer to Fontforge. I'll rectify them in final version.. This is how it looks in my system.. See the attached image..
![screen shot 2016-04-09 at 11 04 45 am](https://cloud.githubusercontent.com/assets/6254102/14418544/060ce4ee-ffdd-11e5-8b0f-bfde41cb9cfe.png)
2. **Just because the typeface is a loose design doesn’t mean we can get sloppy with our outlining.**
Sorry.. I don't agree with this.. I'm still making minor modifications in the glyphs. Once they are complete then I'll remove all the overlaps.

**Comment by appajid** [comment]
I've checked the "union font" uploaded by Kelvin..

The line spacing and character spacing for Kannada reduced. Due to complex combinations of Kannada we cannot reduce line spacing as well as character spacing. If you reduce line spacing then the Below base characters will overlap or too close the the main characters which will give us cluttered feeling.

Also old problem (overlaps) which I removed from Latin characters re appeared again.. See the attached image...
![screen shot 2016-04-11 at 12 29 12 pm](https://cloud.githubusercontent.com/assets/6254102/14419204/bbb3ea6e-ffe1-11e5-8837-95e43c8a368b.png)

**Comment by tayloraswift** [comment]
The character spacing was reduced because eben said the spacing was [“uncomfortably wide”](https://github.com/appajid/Ambarisha/issues/8), and I tend to agree with him. We can’t make the latin look bad just to make the kannada look better.

I am 100% okay with having overlaps in the font, _as long as the overlaps are well-constructed_. Outer edges should at least match up, like in this ‘E’:
![selection_017](https://cloud.githubusercontent.com/assets/2556986/14445095/660cbd8e-0018-11e6-93f2-76d6275870d7.png)
This is not the case for many of the kannada glyphs. I'd also look at deepening the joins because a literal overlap generally doesn't give great results
![selection_016](https://cloud.githubusercontent.com/assets/2556986/14445105/7d94e9a4-0018-11e6-956d-a10f400d12fb.png)

Also I fixed the A, the issue wasn’t overlaps, it was that the wrong point was set as the first point.

**Comment by appajid** [comment]
**The character spacing was reduced because eben said the spacing was “uncomfortably wide”, and I tend to agree with him. We can’t make the latin look bad just to make the kannada look better.**

I agree with you when Latin is concerned. I didn't change character spacing in Latin when I merged it with Kannada. But you reduced it in Kannada also.. Don't apply character spacing in general to all characters except Latin.

But Line spacing should not be reduced as it has effect on Kannada also. Most of the Indian Languages especially South Indian Languages will have complex character combinations which contain Above Base and Below Base Characters which need more line space than Latin characters with accents. Let us not reduce Line space because this font mainly caters to Indian Users.

I don't agree with you related to overlaps..

**Comment by tayloraswift** [comment]
I'm not sure if you meant the sidebearings, which I didn't touch, or the space characters, which I did.

I strongly disagree with your statement that the font “mainly caters to Indian Users”. The latin and kannada components are equally important in the font. If kannada glyphs require extra vertical space, kannada designers should already know to increase the leading? Leading is very easy to pad but to decrease leading requires a lot of annoying math work on the part of the user.

**Comment by tayloraswift** [comment]
Also, how do you “not agree” about the overlaps. I don’t see anything to agree or disagree over. Well-constructed overlaps is just good outlining practice. There is never a design reason to leave overlaps misaligned…

**Comment by davelab6** [comment]
> I strongly disagree with your statement that the font “mainly caters to Indian Users”

If it is not possible to make a single family for all users, Google Fonts can publish a latin only font that is ideal for latin users, and a kannada + latin font that is ideal for indian users. 

> The latin and kannada components are equally important in the font. If kannada glyphs require extra vertical space, kannada designers should already know to increase the leading? Leading is very easy to pad but to decrease leading requires a lot of annoying math work on the part of the user.

Sadly, some browsers will clip the font, so the vertical metrics must have linegap values of 0 and ascent/decent values set to the ymax/ymin of a family. This tends to make the latin part of the family have a much higher default line spacing that latin-only fonts.

**Comment by tayloraswift** [comment]
Fine… is +58 / –518 correct for the OS2/HHead values?

**Comment by davelab6** [comment]
@kelvin13 which file should I look at? 

https://github.com/appajid/Ambarisha/tree/master/fonts has not been updated for 9 days

**Comment by tayloraswift** [comment]
I only changed `union.sfd` i didn't put any built fonts in the repo

**Comment by davelab6** [comment]
Please could you build a new TTF?

**Comment by tayloraswift** [comment]
Done, at `Ambarisha2.otf` and `Ambarisha2.ttf`

**Comment by appajid** [comment]
Updated font and source..

**Comment by davelab6** [comment]
Thank you @appajid !! @kelvin13 please take a look :)

**Comment by tayloraswift** [comment]
I consolidated everything into `Ambarisha-Regular.sfd` but it seems that few of the original problems have been fixed…

**Comment by tayloraswift** [comment]
@appajid ^^

**Comment by appajid** [comment]
Yes Kelvin. Help me by listing problems you found with visuals marked similar to your previous posts. I'll rectify them. I'm rectifying the problems I found already..

**Comment by tayloraswift** [comment]
i see many issues in the first three glyphs already, though i don't think i can be much help in communicating them because there are so many problematic points and i do not know the names of kannada glyphs

basically look out for the following:
- Horizontal/vertical curve points that should be marked as HV points
- Missing Absolute extremas (_especially_ if the extrema is small)
- near-horizontal/vertical curve points that create unnecessary missing extremas that should just be made HV
- two consecutive tangent points, there is rarely a good reason to use them in a curving glyph
- two consecutive and parallel curve points, basically same issue as above
- misaligned overlaps
- awkward monotonicity at the end of a curved stroke (like in /knAA)
- also please fix aforementioned excessive points in the autogenerated glyphs

**Comment by appajid** [comment]
Thanks Kelvin. I request you to modify a couple of glyphs as an example for a better understanding. Upload the modified font. I take it as example to understand and try to rectify remaining glyphs. Thanks once again.

**Comment by tayloraswift** [comment]
I cleaned up the first two kannada glyphs

**Comment by appajid** [comment]
Hi Kelvin,
Thank you for the time and effort.. I didn't find much difference in the glyphs you cleaned up. See the attached images.. Left side character is cleaned by you and the right side character is part of my font..

![screen shot 2016-04-23 at 2 12 51 pm](https://cloud.githubusercontent.com/assets/6254102/14760328/7dfb4240-095e-11e6-8063-7832c346d9e0.png)
![screen shot 2016-04-23 at 2 15 51 pm](https://cloud.githubusercontent.com/assets/6254102/14760329/7e2c05a6-095e-11e6-9fe8-0d304bbfb22a.png)

**Comment by tayloraswift** [comment]
It's supposed to look very close to the glyphs you drew; they are technical cleanups on the outlines. Stuff like marking things HV and hitting extremas with curve points.

**Comment by davelab6** [comment]
Ambarisha, your version has many points that are not needed. These make the
font filesize larger, which is unfortunate for users because as a web font
it will load more slowly.

**Comment by tayloraswift** [comment]
^^

**Comment by appajid** [comment]
I agree with you Dave. When I created all my glyphs in Fontographer they are fine. While taking them to Fontforge may be the extra points are added. See the attached image when it's named as KelvinKannada. you can see left side one in Fontographer and rightside one in fontforge. Same character. Now I am shifting all my glyphs from Fontographer to Fontforge without getting extra points. Give me sometime for that.

![screen shot 2016-04-25 at 6 23 15 pm](https://cloud.githubusercontent.com/assets/6254102/14784528/bab3ff36-0b13-11e6-8921-0733b75b056c.png)

**Comment by davelab6** [comment]
It looks like Fontographer is exporting a TT outline and then FF is opening
it and converting it to a PS outline.

Can your fontographer save as VFB?

If so, you can use vfb2ufo to convert it to UFO, and open the UFO in
FontForge.

https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md#web-font-tools

(Also https://github.com/davelab6/dotfiles/blob/master/Mac.md might be
helpful)

**Comment by appajid** [comment]
Can I close this Issue?

**Comment by davelab6** [comment]
@kelvin13 what do you think? :)

**Comment by tayloraswift** [comment]
sure
