### ISSUE TITLE
Remove overlaps

### ISSUE THREAD

**Issue by davelab6** [appajid/Ambarisha#7]
The `A` and perhaps other glyphs have not had remove overlap applied. 

<img width="974" alt="screen shot 2016-03-02 at 02 29 17" src="https://cloud.githubusercontent.com/assets/261579/13453492/9bff57ae-e01e-11e5-9b95-1ec9467157d8.png">

As mentioned in https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md#toolsbuildpy it could be good to have a 'build script' that does all the neccessary steps from taking the actual SFD sources used for development to the final binary fonts, including remove overlap.

**Comment by appajid** [comment]
i'll update this..

**Comment by davelab6** [comment]
Ping :)

**Comment by tayloraswift** [comment]
Is there a reason the source sfd is…well…empty?

**Comment by davelab6** [comment]
@appajid please check

**Comment by tayloraswift** [comment]
screenshot on my system
![selection_029](https://cloud.githubusercontent.com/assets/2556986/13654382/03b075e2-e626-11e5-9267-81205473fd08.png)

**Comment by davelab6** [comment]
Which version of FontForge are you using, and which version is Ambarisha
using?

**Comment by tayloraswift** [comment]
I am using the default ubuntu version

**Comment by tayloraswift** [comment]
Version 31 July 2012 
guess something broke backwards compatibility

**Comment by tayloraswift** [comment]
i'm gonna try building from repo to see if that one works

**Comment by davelab6** [comment]
Yeah that is super super old :) I'm amazed you could get anything done with
it =)

**Comment by tayloraswift** [comment]
it is what ships with ubuntu software center maybe look into that

**Comment by davelab6** [comment]
@appajid which version of FontForge do you use? :)

**Comment by davelab6** [comment]
@appajid confirmed via IM that he uses the latest versions from github source and last updated around 1 month ago

**Comment by appajid** [comment]
Removed overlaps just now

**Comment by davelab6** [comment]
Great!
