### ISSUE TITLE
More descriptive description of the design in README

### ISSUE THREAD

**Issue by davelab6** [appajid/Ambarisha#8]
It would be great to have a more descriptive description of the project in the README :) 

cc @kelvin13

**Comment by davelab6** [comment]
Ping :)

**Comment by tayloraswift** [comment]
I’ve committed a rough draft though some sentences need revising. For example the part `with the same round contours and gentle shapes present in much smaller-sized handwriting` i didn’t really know how to describe the process of converting a small, high [typographical speed](http://designwithfontforge.com/en-US/What_Is_a_Font.html) design into signage size

**Comment by davelab6** [comment]
@EbenSorkin any tips?

**Comment by EbenSorkin** [comment]
I think that some the language here isn't going to quite seem lucid to professional readers. I am posting a suggestion for a possible revised text in my next post. Before I do I wanted to raise two other issues: 1) the word space seems unnaturally large in this design - for the Latin at least. Maybe it has to be that way for the Non-Latin. But if it doesn't I would definitely look at that again for sure and try smaller ones. 2) The capitals all seem just slightly darker than is ideal to support capital letter intensive languages like German. The effect in with a German text will be a bit like raisin bread. The design is a nice one overall. :-)

**Comment by EbenSorkin** [comment]
Ambarisha is a clean condensed sans typeface with a feeling inspired by the author's own written forms and especially from the forms made when writing at a small size. It offers a distictive character that is maintained across a wide range of sizes. It was made to function well in a display role at large sizes. However its open contours and simple robust design also make it legible at text sizes. It's simple clear shapes make it appropriate for the web and on-screen display as well. Ambarisha personality is intended to be vigorous and firm while also offering a warm and approachable feeling. Consistent care and consideration have been poured into all of the glyphs found in the design.

**Comment by EbenSorkin** [comment]
Let me know if this seems accurate to you.

**Comment by tayloraswift** [comment]
I don't want to call it a "condensed sans" because for me that calls to mind like Vialog or Gill Condensed or some other humanist consensed sans. I always thought of this font is a comic book typeface.

**Comment by davelab6** [comment]
"condensed display sans typeface"?

**Comment by EbenSorkin** [comment]
I don't think anyone else with find it comic-book like. I do respect that you do but a large part of what these texts are for is to allow for search and discovery."condensed display sans typeface" sounds good to me.

**Comment by tayloraswift** [comment]
How about 

Ambarisha is a clean condensed sans typeface with an organic feel inspired by the author's own painted signage designs. It offers a distinctive character that is maintained across a wide range of sizes: it was made to function well in a display role at large sizes, while its open contours and simple robust design also make it legible at text sizes. Its simple clear shapes also make it perfect for web and on-screen display. Ambarisha’s personality is intended to be both vigorous and firm, and warm and approachable. The same personality and consideration has been instilled into all of the glyphs found in the design, making Ambarisha a truly multirange design.

**Comment by davelab6** [comment]
Since there are 2 authors, I propose:

Ambarisha is a clean condensed sans typeface with an organic feel. It began
with the Latin design by Kelvin Song, which was inspired by his own painted
signage designs, and then Ambarisha Darbha extended the design to support
Kannada. It offers a distinctive character that is maintained across a wide
range of sizes. It was made to function well in a display role at large
sizes, while the open contours and robust design make it legible at text
sizes. The simple clear shapes also make it perfect for web and screen
reading. The type's personality is intended to be both vigorous and firm,
warm and approachable. The same personality and consideration has been
instilled into all of the glyphs found in the design, making it a truly
multi-purpose design.

**Comment by EbenSorkin** [comment]
I like it!

**Comment by tayloraswift** [comment]
I’m good with it, but i’d like to be credited as "Kelvin Ma"

**Comment by davelab6** [comment]
Of course :)

**Comment by appajid** [comment]
Soory for the late reply. I'm on vacation.. I like it too.. We can add this to the existing description..

**Comment by appajid** [comment]
Updated Readme description also..
