### ISSUE TITLE
Accented characters stripped from font source

### ISSUE THREAD

**Issue by tayloraswift** [appajid/Ambarisha#9]
not sure how to describe this…but all the punctuation, accented, and special characters are gone from the typeface & replaced with glyphs from a filler font… I don’t understand what happened

![selection_030](https://cloud.githubusercontent.com/assets/2556986/13654981/1d578efa-e62a-11e5-8c79-222f2190d084.png)

**Comment by appajid** [comment]
Hi Kelvin,

The font I received earlier from Dave has only main characters. No special characters. I mentioned that with Dave also.. Anyway we can add them now..

**Comment by tayloraswift** [comment]
That might be a problem because the original font I sent him had kerning pairs

**Comment by tayloraswift** [comment]
@davelab6 Why did Dave only send a subset?  I finished the entire Latin+ font when I sent it to him

**Comment by davelab6** [comment]
I didn't do any subsetting; I guess I sent Ambarisha an early version.

**Comment by appajid** [comment]
Updated Accents just now..

**Comment by davelab6** [comment]
Looking at the new TTF, much better! :) I think these 2 are the only ones that seem unrelated:

<img width="215" alt="screen shot 2016-03-30 at 10 30 57" src="https://cloud.githubusercontent.com/assets/261579/14145625/88f6b666-f662-11e5-9514-a32c7793ff85.png">

**Comment by tayloraswift** [comment]
Amacron needs updating too

**Comment by tayloraswift** [comment]
something is wrong with several of the combining accents too.

Does Ambarisha have the isolated kannada font that I can merge into my latin copy? Unless there are kannada–latin kerning pairs to worry about but i don't think we have any
